### PR TITLE
Update Continuous Integration

### PR DESCRIPTION
**Pull request by sudomakeinstall**
When compiling ITK with `Module_MeshNoise=ON` and `ITK_WRAP_PYTHON=ON`,
ITK fails to build with a number of compilation errors due to the fact
that we are attempting to instantiate the filters over `DynamicMeshTraits`,
but `PointSet`, `Mesh`, `MeshSource`, and `MeshToMeshFilter` have been
instantiated for only `StaticMeshTraits`.  This results in a number of
errors of the form `Nothing known about base class XXX`.  This patch
ensures that the two superclasses (`MeshToMeshFilter` and `MeshSource`)
are wrapped by passing the appropriate option
(`POINTER_WITH_2_SUPERCLASSES`), and explicitly wraps `Mesh` and `PointSet`,
allowing the module to build successfully.

### CODE REVIEW

**Comment by sudomakeinstall** [comment]
The full text of a representative error is as follows:

```
/home/davis/Developer/ITK-MeshNoise/bin/Wrapping/Typedefs/itkAdditiveGaussianNoiseMeshFilter.i:410: Warning 401: Nothing known about base class 'itk::PointSet< float,2,itk::DefaultDynamicMeshTraits< float,2,2,float,float,float > >'. Ignored.
/home/davis/Developer/ITK-MeshNoise/bin/Wrapping/Typedefs/itkAdditiveGaussianNoiseMeshFilter.i:410: Warning 401: Maybe you forgot to instantiate 'itk::PointSet< float,2,itk::DefaultDynamicMeshTraits< float,2,2,float,float,float > >' using %template.
/home/davis/Developer/ITK-MeshNoise/bin/Wrapping/Typedefs/itkAdditiveGaussianNoiseMeshFilter.i:480: Warning 401: Nothing known about base class 'itk::PointSet< float,3,itk::DefaultDynamicMeshTraits< float,3,3,float,float,float > >'. Ignored.
/home/davis/Developer/ITK-MeshNoise/bin/Wrapping/Typedefs/itkAdditiveGaussianNoiseMeshFilter.i:480: Warning 401: Maybe you forgot to instantiate 'itk::PointSet< float,3,itk::DefaultDynamicMeshTraits< float,3,3,float,float,float > >' using %template.
Wrapping/Modules/MeshNoise/CMakeFiles/MeshNoisePython.dir/build.make:201: recipe for target 'Wrapping/Modules/MeshNoise/itkAdditiveGaussianNoiseMeshFilterPython.cpp' failed
make[2]: *** [Wrapping/Modules/MeshNoise/itkAdditiveGaussianNoiseMeshFilterPython.cpp] Error 4
make[2]: *** Deleting file 'Wrapping/Modules/MeshNoise/itkAdditiveGaussianNoiseMeshFilterPython.cpp'
CMakeFiles/Makefile2:55920: recipe for target 'Wrapping/Modules/MeshNoise/CMakeFiles/MeshNoisePython.dir/all' failed
make[1]: *** [Wrapping/Modules/MeshNoise/CMakeFiles/MeshNoisePython.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

I have marked this PR as `WIP` because on my machine, this causes four test failures:

```
The following tests FAILED:
	 12 - PythonTypeTest (Failed)
	 32 - itkImageDuplicatorPythonTest (Failed)
	 70 - itkImageFilterNumPyInputsTest (Failed)
	 86 - PythonMedianImageFilterTest (Failed)
```

The last three seem unrelated to this patch, but on the other hand were passing before I enabled `MeshNoise` and rebuilt.  I am unsure if these are truly errors, or if they are an artifact of the sequence in which I've build/edited/rebuilt on my system.  Waiting to see whether they are re-produced on Travis-CI.

**Comment by jhlegarreta** [comment]
@DVigneault thanks for doing this.

Shouldn't `itk::Mesh` be wrapped in the [ITK base code](https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/Core/Mesh/wrapping)?

`itk::PointSet` is [already wrapped](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/wrapping/itkPointSet.wrap), but I found that it is being wrapped in other files (e.g. [here](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Registration/Common/wrapping/itkBlockMatchingImageFilter.wrap)) as well. Not sure why.

**Comment by sudomakeinstall** [comment]
@jhlegarreta Both `itk::Mesh` and `itk::PointSet` are already wrapped in the main ITK repo over `DefaultStaticMeshTraits` (which is the default).  They are *not* wrapped over `DefaultDynamicMeshTraits`.  You are correct that we could choose to wrap `itk::PointSet` and `itk::Mesh` over `DefaultDynamicMeshTraits` either here or in the files you referenced.  I chose to wrap them here for expediency, though we could obviously remove them in the future if appropriate wrappers were added upstream.

**Comment by jhlegarreta** [comment]
Thanks for the explanation @DVigneault . Personally, I haven't got the bandwidth to address that, so I'm approving the PR.

You may want to open an issue in ITK cross-ref'ing this PR so that when they get the mentioned wrapping, the ones in this repository can be removed.

**Review by jhlegarreta — APPROVED** [review]

**Comment by sudomakeinstall** [comment]
@jhlegarreta As for why you see `itk::PointSet` wrappers in multiple places, that's because in the main `itk::PointSet` file they define wrappers for the `double` coordinate type (over `StaticMeshTraits`):

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/wrapping/itkPointSet.wrap#L14-L17

The `BlockMatching` filter requires a specialized version of `itk::PointSet`, templated over a vector length 3:

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Registration/Common/wrapping/itkBlockMatchingImageFilter.wrap#L9-L12

**Comment by jhlegarreta** [comment]
👍 thanks for the elaborated explanation @DVigneault  !

**Comment by sudomakeinstall** [comment]
@thewtex The VM is running out of disk space when building python packages on Ubuntu.  I assume it's related to this issue https://github.com/actions/virtual-environments/issues/709, though it looks to me as though you've already applied all the mitigations they described to free up disk space.  Not sure if you have any other ideas.

**Review by jhlegarreta — APPROVED** [review]
@DVigneault  You may want to open an issue to keep track of the packaging issues on Windows.

**Comment by thewtex** [comment]
@DVigneault thanks for pushing this forward!


> @thewtex The VM is running out of disk space when building python packages on Ubuntu. I assume it's related to this issue actions/virtual-environments#709, though it looks to me as though you've already applied all the mitigations they described to free up disk space. Not sure if you have any other ideas.

Yes, according to @miketimofeev in the referenced thread:

> Unfortunately, we've faced unpredictable issues when /mnt is used as a working directory
https://github.com/actions/virtual-environments/issues/922
We're going to rollback the changes today.

> _Originally posted by @miketimofeev in https://github.com/actions/virtual-environments/issues/709#issuecomment-632567094_

So let's re-build again tomorrow.

**Comment by sudomakeinstall** [comment]
@thewtex Thanks for the review!  And also thank you so much for all your work on `ITKModuleTemplate`--really made it incredibly easy to put this together.

**Pull request merged**
